apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"name":"agent-policy-reader-binding","namespace":"kagent"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"agent-policy-reader"},"subjects":[{"kind":"ServiceAccount","name":"agent-policy-server","namespace":"kagent"}]}
    creationTimestamp: "2026-03-26T00:46:53Z"
    name: agent-policy-reader-binding
    namespace: kagent
    resourceVersion: "3241065"
    uid: 6dc7a477-4b3e-4822-b595-a1efbc6441ea
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: agent-policy-reader
  subjects:
  - kind: ServiceAccount
    name: agent-policy-server
    namespace: kagent
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"name":"audit-logger-binding","namespace":"kagent"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"audit-logger-role"},"subjects":[{"kind":"ServiceAccount","name":"audit-logger","namespace":"kagent"}]}
    creationTimestamp: "2026-03-25T22:47:23Z"
    name: audit-logger-binding
    namespace: kagent
    resourceVersion: "3200521"
    uid: 0495a5ef-6f17-49d3-978f-0c9b171439b0
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: audit-logger-role
  subjects:
  - kind: ServiceAccount
    name: audit-logger
    namespace: kagent
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: kagent
      meta.helm.sh/release-namespace: kagent
    creationTimestamp: "2026-03-19T10:07:29Z"
    labels:
      app.kubernetes.io/instance: kagent
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: kmcp
      app.kubernetes.io/version: 0.2.7
      control-plane: controller-manager
      helm.sh/chart: kmcp-0.2.7
    name: kagent-kmcp-leader-election-rolebinding
    namespace: kagent
    resourceVersion: "129843"
    uid: 5a424bbe-2219-4a35-b53e-c13738bd0edd
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: kagent-kmcp-leader-election-role
  subjects:
  - kind: ServiceAccount
    name: kagent-kmcp-controller-manager
    namespace: kagent
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: khook
      meta.helm.sh/release-namespace: kagent
    creationTimestamp: "2026-03-21T00:04:14Z"
    labels:
      app.kubernetes.io/instance: khook
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: khook
      app.kubernetes.io/version: v0.0.0-9c3ffe6
      helm.sh/chart: khook-v0.0.0-9c3ffe6
    name: khook-leader-election-rolebinding
    namespace: kagent
    resourceVersion: "818534"
    uid: e977281d-0354-4b91-b234-66e1b95ed5b5
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: khook-leader-election-role
  subjects:
  - kind: ServiceAccount
    name: khook
    namespace: kagent
kind: List
metadata:
  resourceVersion: ""
