"""
cities.py — US cities ranked by population for plumber prospecting.

Top 200 US cities by metro population. Each entry includes the state abbreviation
needed for Overpass API queries and search strings.

Usage:
    from cities import US_CITIES
    for city, state in US_CITIES[:50]:   # first 50
        ...
"""

# (city_name, state_abbreviation)
# Ordered by approximate metro population descending.
# Focus on metros >100k where plumber density is high enough to prospect.
US_CITIES: list[tuple[str, str]] = [
    # Tier 1: Major metros (>1M metro pop)
    ("New York", "NY"),
    ("Los Angeles", "CA"),
    ("Chicago", "IL"),
    ("Houston", "TX"),
    ("Phoenix", "AZ"),
    ("Philadelphia", "PA"),
    ("San Antonio", "TX"),
    ("San Diego", "CA"),
    ("Dallas", "TX"),
    ("Jacksonville", "FL"),
    ("Austin", "TX"),
    ("Fort Worth", "TX"),
    ("San Jose", "CA"),
    ("Columbus", "OH"),
    ("Charlotte", "NC"),
    ("Indianapolis", "IN"),
    ("San Francisco", "CA"),
    ("Seattle", "WA"),
    ("Denver", "CO"),
    ("Nashville", "TN"),
    ("Oklahoma City", "OK"),
    ("Washington", "DC"),
    ("El Paso", "TX"),
    ("Las Vegas", "NV"),
    ("Memphis", "TN"),
    ("Louisville", "KY"),
    ("Baltimore", "MD"),
    ("Milwaukee", "WI"),
    ("Albuquerque", "NM"),
    ("Tucson", "AZ"),
    ("Fresno", "CA"),
    ("Sacramento", "CA"),
    ("Mesa", "AZ"),
    ("Kansas City", "MO"),
    ("Atlanta", "GA"),
    ("Omaha", "NE"),
    ("Colorado Springs", "CO"),
    ("Raleigh", "NC"),
    ("Long Beach", "CA"),
    ("Virginia Beach", "VA"),
    ("Miami", "FL"),
    ("Tampa", "FL"),
    ("Orlando", "FL"),
    ("Minneapolis", "MN"),
    ("Cleveland", "OH"),
    ("Pittsburgh", "PA"),
    ("St. Louis", "MO"),
    ("Cincinnati", "OH"),
    ("Portland", "OR"),
    ("Detroit", "MI"),

    # Tier 2: Mid-major metros (300k–1M)
    ("Chattanooga", "TN"),
    ("Knoxville", "TN"),
    ("Boise", "ID"),
    ("Richmond", "VA"),
    ("Salt Lake City", "UT"),
    ("Birmingham", "AL"),
    ("Tulsa", "OK"),
    ("Wichita", "KS"),
    ("New Orleans", "LA"),
    ("Arlington", "TX"),
    ("Bakersfield", "CA"),
    ("Aurora", "CO"),
    ("Anaheim", "CA"),
    ("Honolulu", "HI"),
    ("Santa Ana", "CA"),
    ("Riverside", "CA"),
    ("Corpus Christi", "TX"),
    ("Lexington", "KY"),
    ("Henderson", "NV"),
    ("Stockton", "CA"),
    ("Saint Paul", "MN"),
    ("Greensboro", "NC"),
    ("Newark", "NJ"),
    ("Lincoln", "NE"),
    ("Plano", "TX"),
    ("Buffalo", "NY"),
    ("Chandler", "AZ"),
    ("Lubbock", "TX"),
    ("Scottsdale", "AZ"),
    ("Reno", "NV"),
    ("Glendale", "AZ"),
    ("Gilbert", "AZ"),
    ("Winston-Salem", "NC"),
    ("North Las Vegas", "NV"),
    ("Norfolk", "VA"),
    ("Chesapeake", "VA"),
    ("Garland", "TX"),
    ("Irving", "TX"),
    ("Hialeah", "FL"),
    ("Fremont", "CA"),
    ("Baton Rouge", "LA"),
    ("Des Moines", "IA"),
    ("Spokane", "WA"),
    ("Tacoma", "WA"),
    ("San Bernardino", "CA"),
    ("Modesto", "CA"),
    ("Fontana", "CA"),
    ("Moreno Valley", "CA"),
    ("Fayetteville", "NC"),
    ("Huntsville", "AL"),

    # Tier 3: Smaller metros with high plumber density (100k–300k)
    ("Savannah", "GA"),
    ("Little Rock", "AR"),
    ("Amarillo", "TX"),
    ("Tallahassee", "FL"),
    ("Grand Rapids", "MI"),
    ("Mobile", "AL"),
    ("Huntington", "WV"),
    ("Augusta", "GA"),
    ("Montgomery", "AL"),
    ("Akron", "OH"),
    ("Shreveport", "LA"),
    ("Dayton", "OH"),
    ("Fort Wayne", "IN"),
    ("Brownsville", "TX"),
    ("Tempe", "AZ"),
    ("Overland Park", "KS"),
    ("McKinney", "TX"),
    ("Frisco", "TX"),
    ("Clarksville", "TN"),
    ("Murfreesboro", "TN"),
    ("Columbia", "SC"),
    ("Midland", "TX"),
    ("Denton", "TX"),
    ("Topeka", "KS"),
    ("Olathe", "KS"),
    ("Thornton", "CO"),
    ("Roseville", "CA"),
    ("Surprise", "AZ"),
    ("Miramar", "FL"),
    ("Pasadena", "TX"),
    ("Mesquite", "TX"),
    ("Killeen", "TX"),
    ("McAllen", "TX"),
    ("Waco", "TX"),
    ("Cape Coral", "FL"),
    ("Lakewood", "CO"),
    ("Sioux Falls", "SD"),
    ("Fort Collins", "CO"),
    ("Peoria", "AZ"),
    ("Springfield", "MO"),
    ("Jackson", "MS"),
    ("Pensacola", "FL"),
    ("Macon", "GA"),
    ("Greenville", "SC"),
    ("Charleston", "SC"),
    ("Wilmington", "NC"),
    ("Ocala", "FL"),
    ("Gainesville", "FL"),
    ("Palm Bay", "FL"),
    ("Lakeland", "FL"),
]

# Convenience: just city names
CITY_NAMES: list[str] = [c[0] for c in US_CITIES]

# State full name → abbrev (for Overpass API which uses full names)
STATE_FULL: dict[str, str] = {
    "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas",
    "CA": "California", "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware",
    "DC": "District of Columbia", "FL": "Florida", "GA": "Georgia", "HI": "Hawaii",
    "ID": "Idaho", "IL": "Illinois", "IN": "Indiana", "IA": "Iowa",
    "KS": "Kansas", "KY": "Kentucky", "LA": "Louisiana", "ME": "Maine",
    "MD": "Maryland", "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota",
    "MS": "Mississippi", "MO": "Missouri", "MT": "Montana", "NE": "Nebraska",
    "NV": "Nevada", "NH": "New Hampshire", "NJ": "New Jersey", "NM": "New Mexico",
    "NY": "New York", "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio",
    "OK": "Oklahoma", "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode Island",
    "SC": "South Carolina", "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas",
    "UT": "Utah", "VT": "Vermont", "VA": "Virginia", "WA": "Washington",
    "WV": "West Virginia", "WI": "Wisconsin", "WY": "Wyoming",
}
